"""
One-command firmware-side setup: make a project able to report its own crashes.

Wiring the crash tracer used to be a manual checklist handed to the user - copy two
files, add them to the Keil project, add an include path, delete the HAL fault stub,
write a blocking UART putchar. All of it is mechanical, so all of it belongs here.

    install_crash_tracer("MDK-ARM/App.uvprojx", uart="USART1", family="f1")

After this the only thing left is application logic, which is the AI's job anyway.
"""
import os
import re
import shutil
from typing import List, Optional

from .project_editor import (
    DEFAULT_GROUP, KeilProjectEditor, EditResult, disable_conflicting_fault_handlers,
)

KIT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TRACER_SOURCES = ("cm_backtrace_lite.c", "cm_backtrace_lite.h")
PORT_FILE = "cm_backtrace_port.c"

# USART register generations. v1 uses SR/DR, v2 uses ISR/TDR. TXE is bit 7 in both, so
# the generated code tests the bit directly instead of a macro whose name moved around
# (USART_SR_TXE -> USART_ISR_TXE -> USART_ISR_TXE_TXFNF on FIFO-capable parts).
_V1_FAMILIES = ("f1", "f2", "f4", "l1")

_PORT_TEMPLATE = '''/**
  * @file    cm_backtrace_port.c
  * @brief   Blocking UART sink for the crash tracer. Generated by AutoDebug.
  *
  * Deliberately register-level and blocking: a HardFault runs at priority -1, where
  * SysTick cannot fire, so anything whose timeout depends on HAL_GetTick() (printf via
  * HAL_UART_Transmit, most retargets) spins forever and emits nothing at all.
  *
  * Regenerate for another port with:
  *     python run_autodebug.py --install-tracer --uart USART2 --family g4
  */
#include "cm_backtrace_lite.h"
{include}

#define CM_BT_UART   {uart}
#define CM_BT_TXE    (1U << 7)      /* TXE is bit 7 of {status_reg} on every STM32 USART */

void cm_backtrace_putchar(char c)
{{
    /* The UART must already be initialised by the application before a crash occurs. */
    while ((CM_BT_UART->{status_reg} & CM_BT_TXE) == 0U) {{
        /* spin: no SysTick, no HAL, no timeout that could never expire */
    }}
    CM_BT_UART->{data_reg} = (uint8_t)c;
}}
'''


def _family_of(target_name: Optional[str]) -> Optional[str]:
    """'stm32f407zg' -> 'f4'."""
    if not target_name:
        return None
    m = re.search(r"stm32([a-z]\d)", target_name.lower())
    return m.group(1) if m else None


def _cmsis_header(family: str) -> str:
    return f'#include "stm32{family}xx.h"'


def generate_uart_port(project_root: str, uart: str = "USART1",
                       family: str = "f1", overwrite: bool = False) -> EditResult:
    """Write cm_backtrace_port.c with a correct blocking putchar for this family."""
    result = EditResult()
    family = (family or "f1").lower()
    uart = (uart or "USART1").upper()
    v1 = family.startswith(_V1_FAMILIES)

    dest_dir = os.path.join(project_root, "mcu_support")
    os.makedirs(dest_dir, exist_ok=True)
    path = os.path.join(dest_dir, PORT_FILE)
    if os.path.exists(path) and not overwrite:
        return result

    text = _PORT_TEMPLATE.format(
        include=_cmsis_header(family),
        uart=uart,
        status_reg="SR" if v1 else "ISR",
        data_reg="DR" if v1 else "TDR",
    )
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    result.add(f"已生成 {PORT_FILE}（{uart}，{'SR/DR' if v1 else 'ISR/TDR'} 寄存器组）")
    return result


def install_crash_tracer(uvprojx_path: str,
                         target_name: Optional[str] = None,
                         uart: Optional[str] = None,
                         family: Optional[str] = None,
                         mcu: Optional[str] = None,
                         group: str = DEFAULT_GROUP) -> EditResult:
    """Copy the tracer in, register it with Keil, and clear the way for it.

    Idempotent: running it again on a project that already has the tracer reports
    "no change needed" and rewrites nothing.
    """
    uvprojx_path = os.path.abspath(uvprojx_path)
    project_root = os.path.dirname(os.path.dirname(uvprojx_path))
    if not os.path.isdir(project_root):
        project_root = os.path.dirname(uvprojx_path)

    result = EditResult()

    # 1. Copy cm_backtrace_lite.{c,h} into the project (kept if already there).
    dest_dir = os.path.join(project_root, "mcu_support")
    os.makedirs(dest_dir, exist_ok=True)
    copied: List[str] = []
    for name in TRACER_SOURCES:
        src = os.path.join(KIT_ROOT, "mcu_support", name)
        dst = os.path.join(dest_dir, name)
        if os.path.exists(dst) or not os.path.exists(src):
            continue
        shutil.copy2(src, dst)
        copied.append(name)
    if copied:
        result.add(f"已拷入 mcu_support/: {', '.join(copied)}")

    # 2. Generate the UART sink when we know which port to use.
    family = (family or _family_of(mcu) or _family_of(target_name) or "").lower()
    if uart and family:
        result.merge(generate_uart_port(project_root, uart, family))
    elif uart and not family:
        result.notes.append(
            f"未能推断芯片系列，跳过 {PORT_FILE} 生成；"
            f"请补 --family（f1/f4/g0/g4/h7 ...）或自行实现 cm_backtrace_putchar")

    # 3. Register the sources and the include path with Keil.
    sources = [os.path.join(dest_dir, "cm_backtrace_lite.c")]
    port_path = os.path.join(dest_dir, PORT_FILE)
    if os.path.exists(port_path):
        sources.append(port_path)

    editor = KeilProjectEditor(uvprojx_path)
    editor.add_sources([s for s in sources if os.path.exists(s)], group=group,
                       target_name=target_name)
    editor.add_include_paths([dest_dir], target_name=target_name)
    editor.set_debug_information(target_name=target_name)
    result.merge(editor.save())

    # 4. Comment out the HAL stubs that would otherwise swallow the crash / clash at link.
    result.merge(disable_conflicting_fault_handlers(project_root))

    if not result.changed:
        result.notes.append("崩溃追踪器已就位，无需改动")
    return result


def check_firmware_contract(project_root: str,
                            pass_keywords: Optional[List[str]] = None) -> List[str]:
    """Report which firmware-side obligations are still unmet.

    Returns a list of human-readable problems; empty means the project is fully wired
    for autonomous diagnosis. Used by the loop to tell the AI what it still owes.
    """
    pass_keywords = pass_keywords or ["[ALL TESTS PASSED]", "TESTS_PASSED", "[PASS]"]
    problems: List[str] = []

    app_blob = ""      # the application's own code
    all_blob = ""      # plus the tracer files we installed
    for root, dirs, files in os.walk(project_root):
        dirs[:] = [d for d in dirs
                   if d not in {".git", "Objects", "Listings", ".autodebug", "__pycache__"}]
        in_tracer = os.path.basename(root).lower() == "mcu_support"
        for name in files:
            if not name.lower().endswith((".c", ".cpp", ".h")):
                continue
            try:
                with open(os.path.join(root, name), encoding="utf-8", errors="replace") as f:
                    text = f.read()
            except Exception:
                continue
            all_blob += text
            if not in_tracer:
                app_blob += text

    # The obligations below must be met by the APPLICATION - finding cm_backtrace_init in
    # the tracer's own header would otherwise mask the fact that nobody ever calls it.
    blob = app_blob

    if not any(kw in blob for kw in pass_keywords):
        problems.append(
            f"没有任何源文件打印通过令牌 {pass_keywords[0]}，"
            f"闭环无法判定成功——请在测试通过路径上打印它")
    if "cm_backtrace_init" not in blob:
        problems.append(
            "main() 里没有调用 cm_backtrace_init()，崩溃时拿不到 CFSR 分类与除零陷阱")
    if "cm_backtrace_putchar" not in all_blob:
        problems.append(
            "没有实现 cm_backtrace_putchar()，崩溃现场无法通过串口输出"
            "（跑 --install-tracer --uart <USARTx> --family <系列> 可自动生成）")

    return problems
